services:
  backend:
    image: ghcr.io/coreruleset/albedo:0.3.0
    command: ["--port", "8081"]
    ports:
      - 8081:8081

  caddy:
    depends_on:
      - backend
    build:
      context: ..
      dockerfile: ./ftw/Dockerfile.caddy
    volumes:
      - ../build:/build
      - .:/conf
    ports:
      - 8080:8080

  coraza-logs:
    depends_on:
      - caddy
    image: debian:13-slim
    entrypoint: bash
    command:
      - -c
      - tail -c +0 -f /build/caddy.log | grep --line-buffered -P '\t(\x1B\[[\d;]+m)?(ERROR|WARN|INFO)(\x1B\[0m)?\thttp.handlers.waf' > /build/ftw.log
    volumes:
      - ../build:/build

  ftw:
    depends_on:
      - coraza-logs
    build:
      context: .
      dockerfile: Dockerfile.ftw
    environment:
      - FTW_CLOUDMODE
      - FTW_INCLUDE
      - FTW_DEBUG
    volumes:
      - ../build:/build
